### ISSUE TITLE
Error when starting rocketchat server.

### ISSUE THREAD

**Issue by bnornholm** [RocketChat/Rocket.Chat.RaspberryPi#16]
/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: No replica set primary available for query with ReadPreference PRIMARY
    at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:395:16)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)
    at setupUsersCollection (accounts_server.js:1413:9)
    at new AccountsServer (accounts_server.js:49:5)
    at Package (globals_server.js:5:12)
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1814:4
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1825:3
    at /home/pi/rocketchat/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
    - - - - -
    at [object Object].ReplSet.checkoutReader (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:619:14)
    at Cursor.nextObject (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
    at Cursor.toArray (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:169:10)
    at Db.indexInformation (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1631:39)
    at Db.ensureIndex (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1498:8)
    at Collection.ensureIndex (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/index.js:68:11)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:789:1)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)
    at setupUsersCollection (accounts_server.js:1413:9)
    at new AccountsServer (accounts_server.js:49:5)

**Comment by Sing-Li** [comment]
this is a problem with access to mongo.  Please close this if you have resolved it. Thanks.

**Comment by vongomben** [comment]
I'm retrieving a similar problem. Here's is my error.

```
/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
MongoError: not authorized on rocketchat to execute command { listIndexes: "users", cursor: {} }
    at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)
    at setupUsersCollection (accounts_server.js:1413:9)
    at new AccountsServer (accounts_server.js:49:5)
    at Package (globals_server.js:5:12)
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1814:4
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1825:3
    at /home/pi/rocketchat/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
    - - - - -
    at Object.toError (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)

```
I'm hosting my mongoDB instance on mlab.com (as adviced bymany) and it says: mongod version: 3.0.12 (MMAPv1).

**Comment by Sing-Li** [comment]
Using latest snap install on the Raspberry Pi 4, these problems have been eliminated.
