### ISSUE TITLE
server won't restart after shutdown

### ISSUE THREAD

**Issue by geosting** [RocketChat/Rocket.Chat.RaspberryPi#22]
I use this code after shutting down my pi
cd /home/pi/rocketchat/bundle
PORT=3000 ROOT_URL=http://localhost:3000 MONGO_URL=mongodb://'user':'password'@':host':'port'/'user'  /home/pi/meteor/dev_bundle/bin/node main.js
but receive the following error message
/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
MongoError: Authentication failed.
    at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at Object.toError (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:31
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)

any reason why I keep getting this ?
thanks

**Comment by Sing-Li** [comment]
Please use the latest snap release on Raspberry Pi 4 or better.
