### ISSUE TITLE
Error: No replica set primary available for query with ReadPreference PRIMARY

### ISSUE THREAD

**Issue by MokaMokiMoke** [RocketChat/Rocket.Chat.RaspberryPi#23]
When installing rocketchat on my Raspberry Pi 2B i get this error

`Error: No replica set primary available for query with ReadPreference PRIMARY                                                               
    at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:395:16)                                 
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)                                                  
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)                                                   
    at setupUsersCollection (accounts_server.js:1413:9)                                                                                     
    at new AccountsServer (accounts_server.js:49:5)                                                                                         
    at Package (globals_server.js:5:12)                                                                                                     
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1762:4                                                          
    at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1773:3                                                          
    at /home/pi/rocketchat/bundle/programs/server/boot.js:242:10                                                                            
    at Array.forEach (native)                                                                                                               
    - - - - -                                                                                                                               
    at [object Object].ReplSet.checkoutReader (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/con
nection/repl_set/repl_set.js:619:14)                                                                                                        
    at Cursor.nextObject (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:748:48)       
    at Cursor.toArray (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:169:10)          
    at Db.indexInformation (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1631:39)        
    at Db.ensureIndex (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1498:8)              
    at Collection.ensureIndex (/home/pi/rocketchat/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/index.js
:68:11)                                                                                                                                     
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:789:1)                                                  
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)                                                   
    at setupUsersCollection (accounts_server.js:1413:9)                                                                                     
    at new AccountsServer (accounts_server.js:49:5)`                                    

My statement line is the following (changed user data)

> PORT=3000 ROOT_URL=http://localhost:3000 MONGO_URL=mongodb://aSampleUser:aPassword@ds033607.mlab.
> com:33607/rocketdb /home/pi/meteor/dev_bundle/bin/node main.js

Used Mongodb version

> mongod version: 3.2.10 (MMAPv1)

Used Raspbian Jessie

> Linux pi21 4.4.26+ #915 Thu Oct 20 17:02:14 BST 2016 armv6l GNU/Linux

I couldn´t find a solution to this problem online. What should i do to get rocketchat running?

**Comment by Sing-Li** [comment]
The snap based install eliminates mishaps such as this.  Please use snap based install on Raspberry Pi 4 or better.
