### ISSUE TITLE
Error: Cannot find module 'fibers'

### ISSUE THREAD

**Issue by halukmy** [RocketChat/Rocket.Chat.RaspberryPi#30]
i tried also everything i still got this

Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/roooocket/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Sing-Li** [comment]
Please follow the installation methods in the *current* README.
